on: [ pull_request, push ]
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master

  make-check:
    name: make check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install dependencies
      run: |
        pip3 install --upgrade -r ./requirements.txt
    - name: make check
      run: |
        make check

  make-linkcheck:
    name: make linkcheck
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install dependencies
      run: |
        pip3 install --upgrade -r ./requirements.txt
    - name: make linkcheck
      id: linkcheck
      run: |
        status=0
        make linkcheck || status=$?
        echo "status=${status}" >> "${GITHUB_OUTPUT}"
        exit 0 # this step should never fail the overall workflow
    - name: Comment on PR if linkcheck failed
      if: ${{ github.event_name == 'pull_request' && steps.linkcheck.outputs.status != 0 }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '⚠️  linkcheck failed with status code ${{ steps.linkcheck.outputs.status }}'
          })
