name: main
on: [ pull_request, push ]
jobs:
  check-pr:
    name: validate commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch origin master
    - uses: flux-framework/pr-validator@master

  make-check:
    name: make check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install dependencies
      run: |
        pip3 install --upgrade -r ./requirements.txt
    - name: make check
      run: |
        make check

  make-linkcheck:
    name: make linkcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install dependencies
      run: |
        pip3 install --upgrade -r ./requirements.txt
    - name: make linkcheck
      run: |
        status=0
        make linkcheck || status=$?
        mkdir -p ./linkcheck
        echo "${status}" > ./linkcheck/status
        echo ${{ github.event.number }} > ./linkcheck/pr_number
        exit 0 # this step should never fail the overall workflow
    - uses: actions/upload-artifact@v4
      with:
        name: linkcheck
        path: linkcheck/
